In [2]:
print("Hello World")

Hello World


In [10]:
aa:list = [1, 2, 3, 4, 5]
bb:tuple = (1, 2, 3, 4, 5)

In [11]:
print(a)

[1, 2, 3, 4, 5]


In [12]:
import numpy as np

In [13]:
c = [1, 2, 3.0]
np.array(a)

array([1, 2, 3, 4, 5])

In [14]:
print(np.array(a))

[1 2 3 4 5]


In [15]:
np_c = np.array(c)

In [16]:
print(np_c)

[1. 2. 3.]


In [20]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((2, 3), 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(4) * 25

array([[25.,  0.,  0.,  0.],
       [ 0., 25.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0., 25.]])

In [24]:
for i in np.arange(0, 10, 1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [28]:
np.arange(0.0, 1.0, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [29]:
np.linspace(0, 10, 5) #0에서 10사이의 구간에 5개의 값을 같은 간격으로 생성

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.logspace(0, 5, 6)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [35]:
np.linspace(0, np.sin(np.pi), 11)

array([0.00000000e+00, 1.22464680e-17, 2.44929360e-17, 3.67394040e-17,
       4.89858720e-17, 6.12323400e-17, 7.34788079e-17, 8.57252759e-17,
       9.79717439e-17, 1.10218212e-16, 1.22464680e-16])

In [42]:
A = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(A, 1, 4, axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [43]:
np.insert(A, 1, [4, 5, 6], axis = 1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [47]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, [1, 2, 3], axis = 1)
print(b)

[[1 1]
 [2 2]
 [3 3]]


In [48]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0 , 1, 2]])
a[1: , 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [49]:
a = np. array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [50]:
print(min(a))

1


In [51]:
a = np.array([[10, 20, 30]])
print(a.mean())

20.0


In [52]:
b = np.array([[1, 1], [2, 2], [3, 3]])
print(b.mean())
f_b = b.flatten()
print(f_b)

2.0
[1 1 2 2 3 3]


In [53]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort()
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [54]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis = 0)
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

In [57]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis = 1)
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [61]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis = 1)
dd = np.flip(d, axis = 1)
print(dd)
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis = 0)
dd = np.flip(d, axis = 0)
print(dd)

[[69 24 55]
 [35 19 11]
 [ 4  1  9]]
[[55 35 24]
 [69 19  9]
 [11  4  1]]


In [62]:
a = np.arange(1, 9)
b = a.reshape(2, 2, 2)
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [87]:
a = np.arange(1, 10)
a = a.reshape(3, 3)
print(a)
b = np.full(9, 3)
b = b.reshape(3, 3)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [88]:
rnd = np.random.randn(5) * 10 + 165 #평균값이 165 표준편차가 10인 값
rnd

array([159.20689188, 162.552519  , 156.59562953, 162.7228002 ,
       160.20824354])

In [120]:
def train_test_split():
    a = np.arange(1, 51)
    np.random.shuffle(a)
    train_Data = a[:40]
    test_Data = a[40:]

    return train_Data, test_Data

(X_train, X_test) = train_test_split()
print(X_train)
print(X_test)

[18 12  3 16 20 37 40 25 21 13 39 22 30 11 44 15 49 41 23 24 46 45 19 36
  4 31 50  6 33 29 42 32  7  2 43 27  8 47  9 28]
[48  5 38 35 17  1 26 34 10 14]


In [122]:
a = np.array([[1, 2], [1, -3]]) # 아 선형 방적식 풀어주는 거구나 #x+2y / x - 3y
b = np.array([6, 1]) #각각 값이 x+2y=6 / x-3y=1
s = np.linalg.solve(a, b) #위 처럼 풀어주는거 !!!
print(a)
print(b)
print(s)

[[ 1  2]
 [ 1 -3]]
[6 1]
[4. 1.]


In [157]:
a = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]])
b = np.array([0, 9, 8])
s = np.linalg.solve(a, b)
print(s)


[1. 2. 3.]


In [124]:
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]], dtype = 'int32')
r = np.linalg.det(a)
print(r)

-11.000000000000002


In [1]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [2]:
b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
c = np.arange(8).reshape(2,4)
c   # (2, 4) 형상의 다차원 배열로 0에서 7까지의 원소를 가짐

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
d = list(range(4))
d   # d는 1차원 리스트로 0에서 3까지의 원소를 가짐

[0, 1, 2, 3]